{% set name = "arch" %}
{% set version = "8.0.0" %}

package:
  name: arch-py
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5e9895c2354b9475aff50797ff2191dc64dc5f79602baf0c9321310fb864b637

build:
  number: 0
  script:
    - export PYTHONUNBUFFERED=1  # [ppc64le]
    # Cross-compilation stuff vendored from numpy-feedstock
    # necessary for cross-compilation to point to the right env
    - export PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig                                    # [build_platform != target_platform]
    - echo "python = '${PREFIX}/bin/python'" >> ${CONDA_PREFIX}/meson_cross_file.txt  # [build_platform != target_platform]
    - MESON_ARGS_REDUCED="$(echo $MESON_ARGS | sed 's/--buildtype release //g')"  # [unix]
    - {{ PYTHON }} -m pip install -vv --no-deps --ignore-installed . -Csetup-args=${MESON_ARGS_REDUCED// / -Csetup-args=}  # [unix]
    - {{ PYTHON }} -m pip install -vv --no-deps --ignore-installed .  # [not unix]
  skip: true  # [py<310 or python_impl == "pypy"]
  
requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=3.0.13                        # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - meson-python                           # [build_platform != target_platform]
    - ninja                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - python
    - pip
    - cython >=3.0.13
    - numpy
    - meson
    - meson-python
    - ninja
    - setuptools
    - setuptools_scm =9.2.0
  run:
    - python
    - pandas >=1.4
    - scipy >=1.8
    - statsmodels >=0.13
    - packaging

test:
  imports:
    - arch
    - arch.unitroot
    - arch.univariate
    - arch.bootstrap
    - arch.covariance
    - arch.data
    - arch.utility
    - arch._version
  commands:
    # do not run test suite in emulation because it takes a long time
    - pip check
    - python -c "import arch; arch.test(['-m', '(not slow)', '--numprocesses', '{{ CPU_COUNT }}'])"  # [(build_platform == target_platform) and (python_impl == "cpython")]
  requires:
    - pip
    - pytest >=8.4.2
    - pytest-xdist

about:
  home: https://github.com/bashtage/arch
  license: NCSA
  license_family: Other
  license_file: LICENSE.md
  summary: Autoregressive Conditional Heteroskedasticity (ARCH) and other tools for financial econometrics
  description: |
    Autoregressive Conditional Heteroskedasticity (ARCH) and other tools for
    financial econometrics, written in Python  (with Cython and/or Numba
    used to improve performance)
  doc_url: https://arch.readthedocs.org/en/latest/
  dev_url: https://github.com/bashtage/arch

extra:
  recipe-maintainers:
    - DanielBok
    - bashtage
