{% set name = "arch" %}
{% set version = "8.0.0" %}

package:
  name: arch-py
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5e9895c2354b9475aff50797ff2191dc64dc5f79602baf0c9321310fb864b637

build:
  number: 0
  script:
    - export PYTHONUNBUFFERED=1  # [ppc64le]
    - {{ PYTHON }} -m pip install -vv --no-deps --ignore-installed .
  skip: true  # [py<310 or python_impl == "pypy"]
  
requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=3.0.13                        # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - setuptools_scm >=9.2.0, <10
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools
    - cython >=3.0.10
    # Do not add any constraint on numpy here to use global pinning
    - numpy
    - meson-python
    - ninja
  run:
    - python
    - pandas >=1.4
    - scipy >=1.8
    - statsmodels >=0.13
    - packaging

test:
  imports:
    - arch
    - arch.unitroot
    - arch.univariate
    - arch.bootstrap
    - arch.covariance
    - arch.data
    - arch.utility
    - arch._version
  commands:
    - pip check
    - python -c "import arch; arch.test(['-m', '(not slow)', '--numprocesses', '{{ CPU_COUNT }}'])"
  requires:
    - pip
    - pytest >=8.4.2
    - pytest-xdist

about:
  home: https://github.com/bashtage/arch
  license: NCSA
  license_family: Other
  license_file: LICENSE.md
  summary: Autoregressive Conditional Heteroskedasticity (ARCH) and other tools for financial econometrics
  description: |
    Autoregressive Conditional Heteroskedasticity (ARCH) and other tools for
    financial econometrics, written in Python  (with Cython and/or Numba
    used to improve performance)
  doc_url: https://arch.readthedocs.org/en/latest/
  dev_url: https://github.com/bashtage/arch

extra:
  recipe-maintainers:
    - DanielBok
    - bashtage
