{% set name = "arch" %}
{% set version = "7.0.0" %}

package:
  name: arch-py
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 353c0dba5242287b8b6b587a70250d788436630bf3b7ef6106f577e45d1ec247

build:
  number: 0
  script:
    - export PYTHONUNBUFFERED=1  # [ppc64le]
    - {{ PYTHON }} -m pip install -vv --no-deps --ignore-installed .
  skip: true  # [py<39]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=3.0.10                        # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools
    - cython >=3.0.10
    # Do not add any constraint on numpy here to use global pinning
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - pandas >=1.4
    - scipy >=1.8
    - statsmodels >=0.12

test:
  imports:
    - arch
    - arch.unitroot
    - arch.univariate
    - arch.bootstrap
    - arch.covariance
    - arch.data
    - arch.utility
    - arch._version
  commands:
    - pip check
  requires:
    - pip
    - packaging

about:
  home: https://github.com/bashtage/arch
  license: NCSA
  license_family: Other
  license_file: LICENSE.md
  summary: Autoregressive Conditional Heteroskedasticity (ARCH) and other tools for financial econometrics
  description: |
    Autoregressive Conditional Heteroskedasticity (ARCH) and other tools for
    financial econometrics, written in Python  (with Cython and/or Numba
    used to improve performance)
  doc_url: https://arch.readthedocs.org/en/latest/
  dev_url: https://github.com/bashtage/arch

extra:
  recipe-maintainers:
    - DanielBok
    - bashtage
