{% set name = "arch" %}
{% set version = "4.12" %}

package:
  name: arch-py
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ee59b1176a3bdfb9604718f43bd6694c7351a44d931b5d6d3ad3697910595521

build:
  number: 0
  script: "{{ PYTHON }} setup.py install --single-version-externally-managed --record=record.txt"
  skip: True  # [py<35]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cython >=0.29
    - pip
    - numpy 1.14.*
  run:
    - python
    - cython >=0.29
    - numpy >=1.14
    - pandas >=0.22
    - scipy >=1.0
    - statsmodels >=0.9

test:
  imports:
    - arch

about:
  home: https://github.com/bashtage/arch
  license: NCSA
  license_family: MIT
  license_file: LICENSE.md
  summary: Autoregressive Conditional Heteroskedasticity (ARCH) and other tools for financial econometrics
  description: |
    Autoregressive Conditional Heteroskedasticity (ARCH) and other tools for financial econometrics, written in Python 
    (with Cython and/or Numba used to improve performance)
  doc_url: https://arch.readthedocs.org/en/latest/
  dev_url: https://github.com/bashtage/arch
  home: https://github.com/bashtage/arch

extra:
  recipe-maintainers:
    - DanielBok
