{% set name = "arch" %}
{% set version = "5.2.0" %}

package:
  name: arch-py
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2dfd1b5f62b72625b8ed430ae0a3e011bbe24b9147c0164bc9e48bf5202dc6ab

build:
  number: 2
  script:
    - export PYTHONUNBUFFERED=1  # [ppc64le]
    - {{ PYTHON }} -m pip install -vv --no-deps --ignore-installed .
  skip: true  # [py<37]

requirements:
  build:
    - {{ compiler('c') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
  host:
    - python
    - cython >=0.29.26
    - pip
    - setuptools
    - setuptools_scm
    # Do not add any constraint on numpy here to use global pinning
    - numpy
  run:
    - python
    - cython >=0.29.26
    - {{ pin_compatible('numpy') }}
    - pandas >=1.0
    - property-cached >=1.6.3
    - scipy >=1.3
    - statsmodels >=0.11

test:
  imports:
    - arch
    - arch.unitroot
    - arch.univariate
    - arch.bootstrap
    - arch.covariance
    - arch.data
    - arch.utility
    - arch._version

about:
  home: https://github.com/bashtage/arch
  license: NCSA
  license_family: Other
  license_file: LICENSE.md
  summary: Autoregressive Conditional Heteroskedasticity (ARCH) and other tools for financial econometrics
  description: |
    Autoregressive Conditional Heteroskedasticity (ARCH) and other tools for
    financial econometrics, written in Python  (with Cython and/or Numba
    used to improve performance)
  doc_url: https://arch.readthedocs.org/en/latest/
  dev_url: https://github.com/bashtage/arch

extra:
  recipe-maintainers:
    - DanielBok
    - bashtage
