build_platform:
  osx_arm64: osx_64
  linux_aarch64: linux_64
test_on_native_only: true
travis:
  secure:
    BINSTAR_TOKEN: VRtncQqJJXyldf4NYNjxpkfBDMVGDiyeP5X/YVzWf+RfMQUmPnBRsl1z/hKXJTWclQomhzq+Dxp31wa3gzCFCgrTbUW/i9imMHvzLK5ssF9Ak6uO2v1D3s09qvYKAmOawIJn3q2AVDVvWmaNKgZQPIoAaM4Y4yTqNhwRLUaGiM3y/qlG56FPZOGdYEZObY0KwcSaGxfPcdOL05h+WYwSZYnuIYlEMpRHkKSqMS7gThCgqxGjVwGoDaFlbGgDriyxNWVXHKuqflRfG7kv3LY7qtN3vo0WSuz0PAqfbStPcOBx2pWC3fzP9e33zISYWYK6wQhk9YBy2oxGlxM+QX28qEixKzD8P9LhymZZn2LxBxIgpf2/2fHz88HmpDg1uPinroMiirAeNUHQmFMCfvmP5Jdsip4Dpwe8x+4q2+Trk7B+Ih5Kn3GiU6KXW2uM3jSYX6BQMXiC1wuYFMHyGKETxQ35PaJo3JynqShJPrAWiiLTf3HEmOwsaFrH7JAluq2dGvpv506JwO1rbWlC+PdgN9fXKMZy/eoAu4YR14KDK/0A2s7PLiRLsq6e6xEWISsWOfby02fmKJOKV/mEf/IUFdIlHLf+px0qYSO9cAXbtB4BA/AtbpCz4re7eGdu3qbhMetmmJT2n61TWxMbhLmTa+KJeopzAG8ezzK7ts3FFkM=
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
bot:
  automerge: true
